#+STARTUP: hidestars
#+STARTUP: indent

#+author: F. Dangel

TODO: How to use with regularization.

* How to make [[https://deepobs.readthedocs.io/en/stable/][DeepOBS]] use [[https://backpack.readthedocs.io/en/latest/][BackPACK]].

Fully-supported problems: ~mnist_logreg~, ~fmnist_2c2d~, ~cifar10_3c3d~, ~cifar100_allcnnc~.

TODO: Need to figure out for problems with regularization.

TODO: Fix ~False~ due to wrong command line calls.

** TODO (make more fine-grained) Overview
#+BEGIN_SRC 
SUMMARY
-------
PROBLEM             | SUPPORTED
cifar10_3c3d        | True
cifar10_vgg16       | True
cifar10_vgg19       | True
cifar100_3c3d       | True
cifar100_allcnnc    | True
cifar100_vgg16      | True
cifar100_vgg19      | True
cifar100_wrn164     | False
cifar100_wrn404     | False
fmnist_2c2d         | True
fmnist_logreg       | True
fmnist_mlp          | True
fmnist_vae          | False
mnist_2c2d          | True
mnist_logreg        | True
mnist_mlp           | True
mnist_vae           | False
quadratic_deep      | False
svhn_3c3d           | True
svhn_wrn164         | False 
#+END_SRC



** Preliminaries 
*** Set up a virtual environment
**** Anaconda
Use the ~.yml~ file to install all required dependencies into a ~conda~ environment named ~backobs~.
#+BEGIN_SRC bash
conda env create -f .conda_env.yml
#+END_SRC
Activate it
#+BEGIN_SRC bash
conda activate backobs
#+END_SRC
**** I don't want to use Anaconda
Make sure you have ~backpack~ and ~deepobs~ installed in your favorite environment.

*** Install ~backobs~
#+BEGIN_SRC bash
pip install -e git://github.com/f-dangel/backobs.git@master#egg=backobs
#+END_SRC
** Example
*** The runner
The [[file:example/][example directory]] contains a [[file:example/runner.py][basic runner]] that integrates BackPACK into DeepOBS test problems. You can modify it to your needs, or leave it as is to run an example.
*** Run SGD on a DeepOBS problem with BackPACK 
There exists a [[file:example/run.py][run script]] you can simply execute from the command line.

Let's run SGD on the MNIST linear regression task with a learning rate of ~0.1~ and momentum of ~0.9~:
#+BEGIN_SRC bash
python example/run.py mnist_logreg --lr 0.1 --momentum 0.9
#+END_SRC

*** Not all problems are supported
ResNets and variational autoencoders are not supported by BackPACK.

For instance, this will crash:
#+BEGIN_SRC 
# WideResNet
python example/run.py svhn_wrn164 --lr 0.1 --momentum 0.9
#+END_SRC

** Tests
*** Reproducing the forward pass manually
Testing [[https://www.backpack.pt][BackPACK]] extensions on a [[https://github.com/fsschneider/DeepOBS][DeepOBS]] problem requires access to the input data. As a first step, we will check here that the forward pass can correctly be reproduced in a manual fashion starting from the mini-batch.

The script ~./test/test_forward.py~ checks for which problems this is possible ($L_2$ regularization is ignored). We check with/without extending the [[https://github.com/fsschneider/DeepOBS][DeepOBS]] problem with [[https://www.backpack.pt][BackPACK]], and with/without adding the regularization term in the forward pass.

Run the following:
#+begin_src bash :results output
  python test/run_test_forward.py
#+end_src 

#+RESULTS:
#+begin_example
✓ [cifar10_3c3d, l2_reg: False, BackPACK: False] DeepOBS: 2.28687, manual: 2.28687
✓ [cifar10_vgg16, l2_reg: False, BackPACK: False] DeepOBS: 2.30151, manual: 2.30151
✓ [cifar10_vgg19, l2_reg: False, BackPACK: False] DeepOBS: 2.30262, manual: 2.30262
✓ [cifar100_3c3d, l2_reg: False, BackPACK: False] DeepOBS: 4.55693, manual: 4.55693
✓ [cifar100_allcnnc, l2_reg: False, BackPACK: False] DeepOBS: 4.56741, manual: 4.56741
✓ [cifar100_vgg16, l2_reg: False, BackPACK: False] DeepOBS: 4.60366, manual: 4.60366
✓ [cifar100_vgg19, l2_reg: False, BackPACK: False] DeepOBS: 4.60555, manual: 4.60555
✓ [cifar100_wrn164, l2_reg: False, BackPACK: False] DeepOBS: 4.31506, manual: 4.31506
✓ [cifar100_wrn404, l2_reg: False, BackPACK: False] DeepOBS: 4.61947, manual: 4.61947
✓ [fmnist_2c2d, l2_reg: False, BackPACK: False] DeepOBS: 2.32473, manual: 2.32473
✓ [fmnist_logreg, l2_reg: False, BackPACK: False] DeepOBS: 2.30259, manual: 2.30259
✓ [fmnist_mlp, l2_reg: False, BackPACK: False] DeepOBS: 2.30591, manual: 2.30591
✓ [fmnist_vae, l2_reg: False, BackPACK: False] DeepOBS: 145.27640, manual: 145.27640
✓ [mnist_2c2d, l2_reg: False, BackPACK: False] DeepOBS: 2.35603, manual: 2.35603
✓ [mnist_logreg, l2_reg: False, BackPACK: False] DeepOBS: 2.30259, manual: 2.30259
✓ [mnist_mlp, l2_reg: False, BackPACK: False] DeepOBS: 2.29524, manual: 2.29524
✓ [mnist_vae, l2_reg: False, BackPACK: False] DeepOBS: 179.56845, manual: 179.56845
❌ [quadratic_deep, l2_reg: False, BackPACK: False] DeepOBS: 5.29617, manual: 4.89908
✓ [svhn_3c3d, l2_reg: False, BackPACK: False] DeepOBS: 2.21970, manual: 2.21970
✓ [svhn_wrn164, l2_reg: False, BackPACK: False] DeepOBS: 1.89063, manual: 1.89063


❌ [cifar10_3c3d, l2_reg: True, BackPACK: False] DeepOBS: 3.54886, manual: 2.28687
❌ [cifar10_vgg16, l2_reg: True, BackPACK: False] DeepOBS: 6.05709, manual: 2.30151
❌ [cifar10_vgg19, l2_reg: True, BackPACK: False] DeepOBS: 6.37784, manual: 2.30262
❌ [cifar100_3c3d, l2_reg: True, BackPACK: False] DeepOBS: 5.94544, manual: 4.55693
❌ [cifar100_allcnnc, l2_reg: True, BackPACK: False] DeepOBS: 4.87410, manual: 4.56741
❌ [cifar100_vgg16, l2_reg: True, BackPACK: False] DeepOBS: 8.40309, manual: 4.60366
❌ [cifar100_vgg19, l2_reg: True, BackPACK: False] DeepOBS: 8.72502, manual: 4.60555
❌ [cifar100_wrn164, l2_reg: True, BackPACK: False] DeepOBS: 4.82936, manual: 4.31506
❌ [cifar100_wrn404, l2_reg: True, BackPACK: False] Raised exception: 'NoneType' object has no attribute 'items'
✓ [fmnist_2c2d, l2_reg: True, BackPACK: False] DeepOBS: 2.32473, manual: 2.32473
✓ [fmnist_logreg, l2_reg: True, BackPACK: False] DeepOBS: 2.30259, manual: 2.30259
✓ [fmnist_mlp, l2_reg: True, BackPACK: False] DeepOBS: 2.30591, manual: 2.30591
✓ [fmnist_vae, l2_reg: True, BackPACK: False] DeepOBS: 145.27640, manual: 145.27640
✓ [mnist_2c2d, l2_reg: True, BackPACK: False] DeepOBS: 2.35603, manual: 2.35603
✓ [mnist_logreg, l2_reg: True, BackPACK: False] DeepOBS: 2.30259, manual: 2.30259
✓ [mnist_mlp, l2_reg: True, BackPACK: False] DeepOBS: 2.29524, manual: 2.29524
✓ [mnist_vae, l2_reg: True, BackPACK: False] DeepOBS: 179.56845, manual: 179.56845
❌ [quadratic_deep, l2_reg: True, BackPACK: False] DeepOBS: 5.29617, manual: 4.89908
❌ [svhn_3c3d, l2_reg: True, BackPACK: False] DeepOBS: 3.48170, manual: 2.21970
❌ [svhn_wrn164, l2_reg: True, BackPACK: False] DeepOBS: 2.37303, manual: 1.89063


✓ [cifar10_3c3d, l2_reg: False, BackPACK: True] DeepOBS: 2.28687, manual: 2.28687
✓ [cifar10_vgg16, l2_reg: False, BackPACK: True] DeepOBS: 2.30151, manual: 2.30151
✓ [cifar10_vgg19, l2_reg: False, BackPACK: True] DeepOBS: 2.30262, manual: 2.30262
✓ [cifar100_3c3d, l2_reg: False, BackPACK: True] DeepOBS: 4.55693, manual: 4.55693
✓ [cifar100_allcnnc, l2_reg: False, BackPACK: True] DeepOBS: 4.56741, manual: 4.56741
✓ [cifar100_vgg16, l2_reg: False, BackPACK: True] DeepOBS: 4.60366, manual: 4.60366
✓ [cifar100_vgg19, l2_reg: False, BackPACK: True] DeepOBS: 4.60555, manual: 4.60555
✓ [cifar100_wrn164, l2_reg: False, BackPACK: True] DeepOBS: 4.31506, manual: 4.31506
✓ [cifar100_wrn404, l2_reg: False, BackPACK: True] DeepOBS: 4.61947, manual: 4.61947
✓ [fmnist_2c2d, l2_reg: False, BackPACK: True] DeepOBS: 2.32473, manual: 2.32473
✓ [fmnist_logreg, l2_reg: False, BackPACK: True] DeepOBS: 2.30259, manual: 2.30259
✓ [fmnist_mlp, l2_reg: False, BackPACK: True] DeepOBS: 2.30591, manual: 2.30591
❌ [fmnist_vae, l2_reg: False, BackPACK: True] Raised exception: 'tuple' object has no attribute 'size'
✓ [mnist_2c2d, l2_reg: False, BackPACK: True] DeepOBS: 2.35603, manual: 2.35603
✓ [mnist_logreg, l2_reg: False, BackPACK: True] DeepOBS: 2.30259, manual: 2.30259
✓ [mnist_mlp, l2_reg: False, BackPACK: True] DeepOBS: 2.29524, manual: 2.29524
❌ [mnist_vae, l2_reg: False, BackPACK: True] Raised exception: 'tuple' object has no attribute 'size'
❌ [quadratic_deep, l2_reg: False, BackPACK: True] DeepOBS: 5.29617, manual: 4.89908
✓ [svhn_3c3d, l2_reg: False, BackPACK: True] DeepOBS: 2.21970, manual: 2.21970
✓ [svhn_wrn164, l2_reg: False, BackPACK: True] DeepOBS: 1.89063, manual: 1.89063


❌ [cifar10_3c3d, l2_reg: True, BackPACK: True] DeepOBS: 3.54886, manual: 2.28687
❌ [cifar10_vgg16, l2_reg: True, BackPACK: True] DeepOBS: 6.05709, manual: 2.30151
❌ [cifar10_vgg19, l2_reg: True, BackPACK: True] DeepOBS: 6.37784, manual: 2.30262
❌ [cifar100_3c3d, l2_reg: True, BackPACK: True] DeepOBS: 5.94544, manual: 4.55693
❌ [cifar100_allcnnc, l2_reg: True, BackPACK: True] DeepOBS: 4.87410, manual: 4.56741
❌ [cifar100_vgg16, l2_reg: True, BackPACK: True] DeepOBS: 8.40309, manual: 4.60366
❌ [cifar100_vgg19, l2_reg: True, BackPACK: True] DeepOBS: 8.72502, manual: 4.60555
❌ [cifar100_wrn164, l2_reg: True, BackPACK: True] DeepOBS: 4.82936, manual: 4.31506
❌ [cifar100_wrn404, l2_reg: True, BackPACK: True] Raised exception: 'NoneType' object has no attribute 'items'
✓ [fmnist_2c2d, l2_reg: True, BackPACK: True] DeepOBS: 2.32473, manual: 2.32473
✓ [fmnist_logreg, l2_reg: True, BackPACK: True] DeepOBS: 2.30259, manual: 2.30259
✓ [fmnist_mlp, l2_reg: True, BackPACK: True] DeepOBS: 2.30591, manual: 2.30591
❌ [fmnist_vae, l2_reg: True, BackPACK: True] Raised exception: 'tuple' object has no attribute 'size'
✓ [mnist_2c2d, l2_reg: True, BackPACK: True] DeepOBS: 2.35603, manual: 2.35603
✓ [mnist_logreg, l2_reg: True, BackPACK: True] DeepOBS: 2.30259, manual: 2.30259
✓ [mnist_mlp, l2_reg: True, BackPACK: True] DeepOBS: 2.29524, manual: 2.29524
❌ [mnist_vae, l2_reg: True, BackPACK: True] Raised exception: 'tuple' object has no attribute 'size'
❌ [quadratic_deep, l2_reg: True, BackPACK: True] DeepOBS: 5.29617, manual: 4.89908
❌ [svhn_3c3d, l2_reg: True, BackPACK: True] DeepOBS: 3.48170, manual: 2.21970
❌ [svhn_wrn164, l2_reg: True, BackPACK: True] DeepOBS: 2.37303, manual: 1.89063


#+end_example
Comments: 
- [ ] *DeepOBS bug?* The forward pass of ~cifar100_wrn404~ does not work with regularization.
- [X] *Variational auto-encoders* mess with IO storing in [[https://www.backpack.pt][BackPACK]], which is expected.
- [ ] *Non-deterministic problem*: The forward pass in ~quadrati_deep~ is not deterministic, with or without [[https://www.backpack.pt][BackPACK]]. At least, the losses only differ between manual/DeepOBS forward pass.
- [X] *Regularized problems* are different from the manual forward pass, as the latter only considers the empirical risk term without regularization. This is expected

