#+STARTUP: hidestars
#+STARTUP: indent

#+author: F. Dangel

* How to make [[https://deepobs.readthedocs.io/en/stable/][DeepOBS]] use [[https://backpack.readthedocs.io/en/latest/][BackPACK]].

Fully-supported problems: ~mnist_logreg~, ~fmnist_2c2d~, ~cifar10_3c3d~, ~cifar100_allcnnc~.

TODO: Need to figure out for problems with regularization.

TODO: Fix ~False~ due to wrong command line calls.
#+BEGIN_SRC 
SUMMARY
-------
PROBLEM             | SUPPORTED
cifar10_3c3d        | True
cifar10_vgg16       | True
cifar10_vgg19       | True
cifar100_3c3d       | True
cifar100_allcnnc    | True
cifar100_vgg16      | True
cifar100_vgg19      | True
cifar100_wrn164     | False
cifar100_wrn404     | False
fmnist_2c2d         | True
fmnist_logreg       | True
fmnist_mlp          | True
fmnist_vae          | False
mnist_2c2d          | True
mnist_logreg        | True
mnist_mlp           | True
mnist_vae           | False
quadratic_deep      | False
svhn_3c3d           | True
svhn_wrn164         | False 
#+END_SRC


** Preliminaries 
*** Set up a virtual environment
**** Anaconda
Use the ~.yml~ file to install all required dependencies into a ~conda~ environment named ~backobs~.
#+BEGIN_SRC bash
conda env create -f .conda_env.yml
#+END_SRC
Activate it
#+BEGIN_SRC bash
conda activate backobs
#+END_SRC
**** I don't want to use Anaconda
Make sure you have ~backpack~ and ~deepobs~ installed in your favorite environment.

*** Install ~backobs~
#+BEGIN_SRC bash
pip install -e git://github.com/f-dangel/backobs.git@master#egg=backobs
#+END_SRC
** Example
*** The runner
The [[file:example/][example directory]] contains a [[file:example/runner.py][basic runner]] that integrates BackPACK into DeepOBS test problems. You can modify it to your needs, or leave it as is to run an example.
*** Run SGD on a DeepOBS problem with BackPACK 
There exists a [[file:example/run.py][run script]] you can simply execute from the command line.

Let's run SGD on the MNIST linear regression task with a learning rate of ~0.1~ and momentum of ~0.9~:
#+BEGIN_SRC bash
python example/run.py mnist_logreg --lr 0.1 --momentum 0.9
#+END_SRC

*** Not all problems are supported
For instance, this will crash as BackPACK does not support ResNets yet:
#+BEGIN_SRC 
python example/run.py svhn_wrn164 --lr 0.1 --momentum 0.9
#+END_SRC
